name: Build Linux

env:
  project: PopEngine
  AUTH_TOKEN: ${{ secrets.PACKAGE_KEY_ACTIONS }}

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-18.04
            type: linux
            arch: x86_64
            
          # gr: osmesa build missing egl symbols when linking test app... eglCreateContext temporarily disabling
          #- os: ubuntu-18.04
          #  type: linux
          #  arch: x86_64
          #  flag: osmesa

          # gr: temporarily disabling to get a linux build going
          #- os: Nvidia
          #  type: linux
          #  arch: arm64

          # - os: Pi4
          #   type: linux

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@newchromantics'
          node-version: 12
  
      - name: Install Github Packages
        working-directory: ${{ env.project }}.Package/
        run: |
          npm install
          npm list
        env:
          NODE_AUTH_TOKEN: ${{ env.AUTH_TOKEN }}

      - name: Linux
        uses: NewChromantics/PopAction_BuildLinux@v1
        with:
          lib_dir: ${{ matrix.config.os }}
          os: ${{ matrix.config.os }}
          project: ${{ env.project }}
          arch: ${{ matrix.config.arch }}
          flag: ${{ matrix.config.flag }}

