name: Build Apple
env:
  project: PopEngine
  AUTH_TOKEN: ${{ secrets.PACKAGE_KEY_ACTIONS }}

on:
  push:
    branches:
      - master
      - '*Test*'
jobs:
  Test:
    name: Universal
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: "Import Apple-Distriubution NewChromantics Signing Certificate"
        if: matrix.config.os == 'macos-latest'
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.APPLE_DIST_NEWCHROMANTICS_P12 }}
          certificate-passphrase: ${{ secrets.APPLE_DIST_NEWCHROMANTICS_PASSWORD }}
          keychain-password: "Hello"

      - uses: NewChromantics/PopAction_BuildApple@v1.0.9
        with:
          BuildScheme: ${{ env.project }}_Universal
          project: ${{ env.project }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.UPLOAD_DIR }}
